# Updates website for a GAP release
name: "Update website"

on: 
  push:
    branches:
      - website-scripts # This is temporary; currently you can only manually dispatch workflows those exist on the master branch, and obviously this stuff isn't merged yet. I will test it on my fork before making a PR.
  workflow_dispatch:
    inputs:
      input1:
        description: "Input #1"
        required: true
        default: "do we need inputs?"
      tag:
        description: "Release tag name"

jobs:
  website:
    name: "Update the website based on a GAP release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Clone GAP master to get its release scripts"
        shell: bash
        run: |
          git clone -b website-scripts --depth=1 https://github.com/wilfwilson/gap.git tmp/gap
      - name: "Set up Python"
        uses: actions/setup-python@v2
      - name: "Install Python modules"
        run: pip3 install PyGithub requests python-dateutil
      - name: "Run GAP script dev/releases/update_website.py"
        run: python -u ./tmp/gap/dev/releases/update_website.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Make a PR"
        uses: peter-evans/create-pull-request@v3
        with:
          #token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "This is cool!"
